# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Studium
email: caleb.bassett@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A journal of confessional language studies
baseurl: "/" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com

# Collections

collections_dir: collections
collections:
  authors:
    output: true
    permalink: /author/:name
  translations:
    output: true
    permalink: /translation/:name
  contributors:
    output: true
    permalink: /translator/:name
  authors:
    output: true
    permalink: /author/:name:output_ext
  bios:
    output: true
    permalink: /author/:name
    
# Defaults

defaults:
  - scope:
      path: ""
      type: "translations"
    values:
      layout: "translation"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "bios"
    values:
      layout: "bio"
  - scope:
      path: ""
      type: "contributors"
    values:
      layout: "contributor"
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Global Variables

onote: '<span class="badge badge-dark">Original</span>'
tnote: '<span class="badge badge-info">Translator</span>'